FROM python:3
# /usr/local/bin/python3


RUN pip install jsonlib-python3 requests pandas
#RUN apt-get update && apt-get install -y \
#    vim
#ENV PYTHONPATH="/usr/local/lib/python3.8/site-packages:/opt/VEP_Filter/src/python"

#WORKDIR /opt

#COPY docker/vimrc /root/.vimrc
#COPY . /opt/python3_gdc
